database:
  type: "mysql" #h2, mysql, postgresql,
  host: ""
  database: ""
  username: ""
  password: ""
  table-prefix: ""
features:
  base:
    enabled: true
    permissions:
      reload: test.reload